### ISSUE TITLE
[v2.2.3] [Ubuntu 22.04] /opt/scalyr-agent-2 directory is missing some files

### ISSUE THREAD

**Issue by Kami** [scalyr/scalyr-agent-2#1179] opened 2023-08-15 07:20 UTC
I'm running v2.2.3 release on Ubuntu 22.04.

Release notes document (https://github.com/scalyr/scalyr-agent-2/blob/master/RELEASE_NOTES.md) claims the package layout has changed and packages now ship with their own Python interpreter (aka AIO packages were made default it seems).

The problem is that release notes claim there should be files in `/opt/scalyr-agent-2/bin/`, but that doesn't appear to be the case.

```bash
$ ls -la /opt/scalyr-agent-2
total 12
drwxr-xr-x  3 root root 4096 Mar 23 14:06 .
drwxr-xr-x 27 root root 4096 Apr 21 20:38 ..
drwxr-xr-x  2 root root 4096 Aug 14 20:21 etc
$ ls -la /opt/scalyr-agent-2/etc
total 16
drwxr-xr-x 2 root root 4096 Aug 14 20:21 .
drwxr-xr-x 3 root root 4096 Mar 23 14:06 ..
-rw-r--r-- 1 root root  185 Aug 14 20:21 additional-requirements.txt
-rw-r--r-- 1 root root    4 Mar  2 14:34 preferred_openssl
$ ls -la /opt/scalyr-agent-2/bin
ls: cannot access '/opt/scalyr-agent-2/bin': No such file or directory
```

This looks like a packaging bug. It's a bit of a blocker since it means I can't initialize virtual environment with custom dependencies which are needed for custom monitors which I'm running.

**Comment by tomaz-s1** [comment] 2023-08-28 15:02
I discussed this with @alesnovak-s1 on Slack.

He was not able to reproduce it (clean installation, upgrade from pre 2.2.0 to the latest version) so I will go ahead and close this as "can't produce" / "possibly issue on the user (my) side".

**Closed by tomaz-s1** 2023-08-28 15:02 UTC
